Add a client example written in React
arkhn/identity-provider pull request #28
Opened 2020-10-15 13:32 UTC by Jasopaum

2020-10-15 13:37 UTC, elsiehoffet-94 approved these changes
👏 Cool, thanks!

2020-10-15 14:38 UTC, simonvadee requested changes

2020-10-15 14:38 UTC, simonvadee commented on example-client-react/package.json
> +    "typescript": "~3.7.2"
please split dependencies and devDependencies

2020-10-15 14:38 UTC, simonvadee commented on example-client-react/src/components/home/index.tsx
> +        <p>Connected with token starting with {accessToken.substring(0, 15)}</p>
I think you can display the whole token here ?

2020-10-19 12:56 UTC, Jasopaum commented on example-client-react/src/App.tsx
> +};
It's not, indeed 👍

2020-10-19 17:14 UTC, simonvadee approved these changes

2020-10-19 17:15 UTC, merged